# Generated by Django 3.0.2 on 2020-01-28 22:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Board',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=15)),
                ('status', models.BooleanField(choices=[(True, 'ACTIVATED'), (False, 'DEACTIVATED')], default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Pin',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.PositiveIntegerField(db_index=True)),
                ('status', models.CharField(max_length=4)),
                ('mode', models.BooleanField(choices=[(True, 'INPUT'), (False, 'OUTPUT')], default=False)),
                ('configuration', models.IntegerField(choices=[(0, 'DIGITAL'), (1, 'ANALOG'), (2, 'PWM')])),
                ('description', models.CharField(blank=True, max_length=256, null=True)),
                ('board', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='board.Board')),
            ],
        ),
    ]
