# Generated by Django 3.1 on 2020-08-18 01:10

import board.core.validators
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Board',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=15, unique=True)),
                ('status', models.IntegerField(choices=[(1, 'Deactivated'), (2, 'Activated'), (3, 'Blocked')])),
                ('password', models.TextField(validators=[django.core.validators.MinLengthValidator(12)])),
            ],
        ),
        migrations.CreateModel(
            name='Pin',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('number', models.PositiveIntegerField()),
                ('value', models.CharField(max_length=3, validators=[board.core.validators.validate_pin_value])),
                ('is_digital', models.BooleanField(default=True)),
                ('description', models.CharField(max_length=512, null=True)),
                ('board', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='board.board')),
            ],
        ),
        migrations.AddIndex(
            model_name='board',
            index=models.Index(fields=['created'], name='board_board_created_30845b_idx'),
        ),
        migrations.AddIndex(
            model_name='board',
            index=models.Index(fields=['updated'], name='board_board_updated_d6bcc5_idx'),
        ),
        migrations.AddIndex(
            model_name='board',
            index=models.Index(fields=['status'], name='board_board_status_715e63_idx'),
        ),
        migrations.AddIndex(
            model_name='pin',
            index=models.Index(fields=['created'], name='board_pin_created_09f544_idx'),
        ),
        migrations.AddIndex(
            model_name='pin',
            index=models.Index(fields=['updated'], name='board_pin_updated_e6732d_idx'),
        ),
        migrations.AddIndex(
            model_name='pin',
            index=models.Index(fields=['number'], name='board_pin_number_ac636c_idx'),
        ),
        migrations.AddIndex(
            model_name='pin',
            index=models.Index(fields=['value'], name='board_pin_value_cb382b_idx'),
        ),
        migrations.AddIndex(
            model_name='pin',
            index=models.Index(fields=['is_digital'], name='board_pin_is_digi_a536dc_idx'),
        ),
        migrations.AddConstraint(
            model_name='pin',
            constraint=models.UniqueConstraint(fields=('number', 'board'), name='pin_constraint'),
        ),
    ]
