# Generated by Django 3.1 on 2020-08-11 22:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pin',
            name='mode',
        ),
    ]
