# Generated by Django 3.0.2 on 2020-01-28 22:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='board',
            name='name',
            field=models.CharField(db_index=True, max_length=15, unique=True),
        ),
    ]
