# Generated by Django 3.0.8 on 2020-07-25 00:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_celery_beat', '0012_periodictask_expire_seconds'),
        ('board', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pin',
            name='periodic_behaviors',
            field=models.ManyToManyField(to='django_celery_beat.PeriodicTask'),
        ),
    ]
