# Generated by Django 3.0.2 on 2020-01-31 23:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0002_auto_20200128_2240'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pin',
            name='description',
            field=models.TextField(blank=True, max_length=256, null=True),
        ),
        migrations.AddConstraint(
            model_name='pin',
            constraint=models.UniqueConstraint(fields=('number', 'board'), name='pin_constraint'),
        ),
    ]
