# Generated by Django 3.1 on 2020-08-11 22:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0002_remove_pin_mode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pin',
            name='description',
            field=models.CharField(max_length=512, null=True),
        ),
    ]
