# Generated by Django 3.0.8 on 2020-07-31 01:59

import board.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0002_pin_periodic_behaviors'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pin',
            name='mode',
        ),
        migrations.AlterField(
            model_name='pin',
            name='value',
            field=models.CharField(max_length=3, null=True, validators=[board.validators.validate_pin_value]),
        ),
    ]
