# Generated by Django 3.0.4 on 2020-03-08 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0003_auto_20200131_2319'),
    ]

    operations = [
        migrations.AddField(
            model_name='board',
            name='password',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
    ]
