# Generated by Django 3.0.4 on 2020-03-08 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0005_auto_20200308_1917'),
    ]

    operations = [
        migrations.AlterField(
            model_name='board',
            name='password',
            field=models.CharField(max_length=100),
        ),
    ]
