# Generated by Django 3.0.4 on 2020-03-08 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0006_auto_20200308_1918'),
    ]

    operations = [
        migrations.AddField(
            model_name='board',
            name='allowed',
            field=models.BooleanField(default=True),
        ),
    ]
