# Generated by Django 3.0.4 on 2020-03-08 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0007_board_allowed'),
    ]

    operations = [
        migrations.AddField(
            model_name='board',
            name='last_request',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
    ]
