# Generated by Django 3.0.4 on 2020-03-08 22:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0008_board_last_request'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pin',
            name='board',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, to='board.Board'),
        ),
    ]
