# Generated by Django 3.1 on 2020-08-12 20:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('christine', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='christineresponse',
            name='id',
        ),
        migrations.AlterField(
            model_name='christineresponse',
            name='message',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='christine.message'),
        ),
    ]
