# Generated by Django 3.0.2 on 2020-02-10 23:58

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='correios',
            name='code',
            field=models.CharField(db_index=True, max_length=13, validators=[django.core.validators.RegexValidator(regex='^\\w{13}$')]),
        ),
    ]
