# Generated by Django 3.0.2 on 2020-02-09 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='correios',
            name='last_update',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
