# Generated by Django 3.1.2 on 2020-11-02 22:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('microcontrollers', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pin',
            name='description',
            field=models.CharField(blank=True, max_length=512, null=True),
        ),
    ]
