# Generated by Django 3.1 on 2020-08-18 02:00

import boards.core.validators
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Board',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=15, unique=True)),
                ('status', models.IntegerField(choices=[(1, 'Deactivated'), (2, 'Activated'), (3, 'Blocked')])),
                ('password', models.TextField(validators=[django.core.validators.MinLengthValidator(12)])),
            ],
        ),
        migrations.CreateModel(
            name='Pin',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('number', models.PositiveIntegerField()),
                ('value', models.CharField(max_length=3, validators=[boards.core.validators.validate_pin_value])),
                ('is_digital', models.BooleanField(default=True)),
                ('description', models.CharField(max_length=512, null=True)),
                ('board', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='boards.board')),
            ],
        ),
        migrations.AddIndex(
            model_name='board',
            index=models.Index(fields=['created'], name='boards_boar_created_2c4776_idx'),
        ),
        migrations.AddIndex(
            model_name='board',
            index=models.Index(fields=['updated'], name='boards_boar_updated_2e32e5_idx'),
        ),
        migrations.AddIndex(
            model_name='board',
            index=models.Index(fields=['status'], name='boards_boar_status_2854ea_idx'),
        ),
        migrations.AddIndex(
            model_name='pin',
            index=models.Index(fields=['created'], name='boards_pin_created_457cf3_idx'),
        ),
        migrations.AddIndex(
            model_name='pin',
            index=models.Index(fields=['updated'], name='boards_pin_updated_ad879e_idx'),
        ),
        migrations.AddIndex(
            model_name='pin',
            index=models.Index(fields=['number'], name='boards_pin_number_361224_idx'),
        ),
        migrations.AddIndex(
            model_name='pin',
            index=models.Index(fields=['value'], name='boards_pin_value_ac701d_idx'),
        ),
        migrations.AddIndex(
            model_name='pin',
            index=models.Index(fields=['is_digital'], name='boards_pin_is_digi_3dda3b_idx'),
        ),
        migrations.AddConstraint(
            model_name='pin',
            constraint=models.UniqueConstraint(fields=('number', 'board'), name='pin_constraint'),
        ),
    ]
