# Generated by Django 3.1 on 2020-08-26 23:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0001_initial'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='pin',
            constraint=models.CheckConstraint(check=models.Q(models.Q(('is_digital', True), ('value__regex', 'ON|OFF')), models.Q(('is_digital', False), ('value__regex', '^\\d+$')), _connector='OR'), name='pin_value_by_type'),
        ),
    ]
