# Generated by Django 3.0.2 on 2020-02-10 22:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Correios',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(db_index=True, max_length=13)),
                ('name', models.CharField(db_index=True, max_length=100)),
                ('delivered', models.BooleanField(db_index=True, default=False)),
                ('last_update', models.DateTimeField(blank=True, null=True)),
                ('cpf_registered', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='CorreiosInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField()),
                ('place', models.CharField(max_length=100)),
                ('status', models.CharField(max_length=100)),
                ('info', models.TextField()),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orders.Correios')),
            ],
        ),
    ]
