# Generated by Django 3.1 on 2020-08-07 03:54

import django.core.validators
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_auto_20200210_2358'),
    ]

    operations = [
        migrations.AddField(
            model_name='correios',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='correios',
            name='updated',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='correiosinfo',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='correiosinfo',
            name='updated',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='correios',
            name='code',
            field=models.CharField(max_length=13, validators=[django.core.validators.RegexValidator(regex='^\\w{2}\\d{9}\\w{2}$')]),
        ),
        migrations.AlterField(
            model_name='correios',
            name='delivered',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='correios',
            name='last_update',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='correios',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AddIndex(
            model_name='correios',
            index=models.Index(fields=['created'], name='orders_corr_created_fdf41b_idx'),
        ),
        migrations.AddIndex(
            model_name='correios',
            index=models.Index(fields=['updated'], name='orders_corr_updated_ff1d9c_idx'),
        ),
        migrations.AddIndex(
            model_name='correios',
            index=models.Index(fields=['code'], name='orders_corr_code_12dff5_idx'),
        ),
        migrations.AddIndex(
            model_name='correios',
            index=models.Index(fields=['name'], name='orders_corr_name_a139d8_idx'),
        ),
        migrations.AddIndex(
            model_name='correios',
            index=models.Index(fields=['delivered'], name='orders_corr_deliver_1ec6c8_idx'),
        ),
        migrations.AddConstraint(
            model_name='correios',
            constraint=models.UniqueConstraint(condition=models.Q(delivered=False), fields=('code',), name='delivery'),
        ),
    ]
